
# cargo-vet audits file

[[audits.cc]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "1.2.59 -> 1.2.60"

[[audits.embassy-executor]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.9.1 -> 0.10.0"

[[audits.embassy-executor-macros]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.7.0 -> 0.8.0"

[[audits.libc]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.2.184 -> 0.2.185"
